languageCode = "en"
languageName = "English"
weight = 1

[params]
    rtl = false
    description = "The Math Graduate Board (MGB) exists to provide a forum for departmental discourse"
    dateFormat = "2 January 2006"
    displayName = "EN"
    isoCode = "en"

title = "University of Iowa Math Graduate Board"
# logo = "img/blowfish_logo_transparent.png"


# [author]
#   name = "Blowfish"
#   image = "img/blowfish_logo.png"
#   headline = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
#   bio = "A powerful, lightweight theme for Hugo built with Tailwind CSS."
#   links = [
#     { twitter = "https://twitter.com/burufugu" },
#     { mastodon = "https://masto.ai/@blowfish" },
#     { github = "https://github.com/nunocoracao/blowfish" },
#   ]
