# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
#
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "Blog"
  pageRef = "Blog"
  weight = 50

[[main]]
  name = "GAUSS"
  pageRef = "GAUSS"
  weight = 40

[[main]]
  name = "Minutes"
  pageRef = "Minutes"
  weight = 20

[[main]]
  name = "Newsletter"
  pageRef = "Newsletter"
  weight = 30

[[main]]
  name = "Officers"
  pageRef = "Officers"
  weight = 10

[[main]]
  name = "Resources"
  pageRef = "Resources"
  weight = 60


#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000

[[main]]
  identifier = "Youtube"
  pre = "Youtube"
  url = "https://www.youtube.com/@universityofiowamathgradua4229"
  weight = 1

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/uiowa-mgb"
  weight = 1


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

#  [[footer]]
#    name = "Tags"
#    pageRef = "tags"
#    weight = 10
